(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const l=[{name:"Jane Cooper",company:"Microsoft",phone:"(225) 555-0118",email:"jane@microsoft.com",country:"United States",status:"Active"},{name:"Floyd Miles",company:"Yahoo",phone:"(205) 555-0100",email:"floyd@yahoo.com",country:"Kiribati",status:"Inactive"},{name:"Ronald Richards",company:"Adobe",phone:"(302) 555-0107",email:"ronald@adobe.com",country:"Israel",status:"Inactive"},{name:"Marvin McKinney",company:"Tesla",phone:"(252) 555-0126",email:"marvin@tesla.com",country:"Iran",status:"Active"},{name:"Jerome Bell",company:"Google",phone:"(629) 555-0129",email:"jerome@google.com",country:"Réunion",status:"Active"},{name:"Kathryn Murphy",company:"Microsoft",phone:"(406) 555-0120",email:"kathryn@microsoft.com",country:"Curaçao",status:"Active"},{name:"Jacob Jones",company:"Yahoo",phone:"(208) 555-0112",email:"jacob@yahoo.com",country:"Brazil",status:"Active"},{name:"Kristin Watson",company:"Facebook",phone:"(704) 555-0127",email:"kristin@facebook.com",country:"Åland Islands",status:"Inactive"}],r=document.querySelector(".table");l.forEach(n=>{const o=document.createElement("tr");o.innerHTML=`
    <td class="table-text">${n.name}</td>
    <td class="table-text">${n.company}</td>
    <td class="table-text">${n.phone}</td>
    <td class="table-text">${n.email}</td>
    <td class="table-text">${n.country}</td>
    <td class="table-text status"><span class="status-block">${n.status}</span></td>
  `,r.appendChild(o);const a=document.createElement("tr");a.innerHTML=`
  <td colspan="6">
    <div class="linerow"></div>
  </td>
`,r.appendChild(a)});const d=document.querySelectorAll(".status-block");d.forEach(n=>{n.textContent==="Active"?n.classList.add("active"):n.classList.add("inactive")});(()=>{const n=document.querySelector(".js-menu"),o=document.querySelector(".js-menu-open"),a=document.querySelector(".js-menu-close"),c=document.querySelectorAll(".menu-link"),e=()=>{const t=o.getAttribute("aria-expanded")==="true"||!1;o.setAttribute("aria-expanded",!t),n.classList.toggle("is-open")};o.addEventListener("click",e),a.addEventListener("click",e),c.forEach(t=>{t.addEventListener("click",e)}),window.matchMedia("(min-width: 1440px)").addEventListener("change",t=>{t.matches&&(n.classList.remove("is-open"),o.setAttribute("aria-expanded",!1))})})();const i=document.querySelectorAll(".menu-link");i.forEach(n=>{n.addEventListener("click",o=>{o.preventDefault(),i.forEach(a=>a.classList.remove("current")),(void 0).classList.add("current")})});
//# sourceMappingURL=commonHelpers.js.map
